// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg5iqo2lFv5UIVJFL9Ew1KmQgNUloIItI',
    appId: '1:1094066049572:web:1383eac0723bef51b3beb1',
    messagingSenderId: '1094066049572',
    projectId: 'cw12-a4842',
    authDomain: 'cw12-a4842.firebaseapp.com',
    storageBucket: 'cw12-a4842.firebasestorage.app',
    measurementId: 'G-VWQ51TJRN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwbcV1bYpGpkwYU0sB6faL0FKkyuO38VA',
    appId: '1:1094066049572:android:0bd4d5a0b2ab70b3b3beb1',
    messagingSenderId: '1094066049572',
    projectId: 'cw12-a4842',
    storageBucket: 'cw12-a4842.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRP7kzFPiAstCVLXXfJChKAAYx13O8oo',
    appId: '1:1094066049572:ios:b61fa83fcb5f5a2cb3beb1',
    messagingSenderId: '1094066049572',
    projectId: 'cw12-a4842',
    storageBucket: 'cw12-a4842.firebasestorage.app',
    iosBundleId: 'com.example.cw11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATRP7kzFPiAstCVLXXfJChKAAYx13O8oo',
    appId: '1:1094066049572:ios:b61fa83fcb5f5a2cb3beb1',
    messagingSenderId: '1094066049572',
    projectId: 'cw12-a4842',
    storageBucket: 'cw12-a4842.firebasestorage.app',
    iosBundleId: 'com.example.cw11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg5iqo2lFv5UIVJFL9Ew1KmQgNUloIItI',
    appId: '1:1094066049572:web:c00fc5b71384452eb3beb1',
    messagingSenderId: '1094066049572',
    projectId: 'cw12-a4842',
    authDomain: 'cw12-a4842.firebaseapp.com',
    storageBucket: 'cw12-a4842.firebasestorage.app',
    measurementId: 'G-X5JMM1RN80',
  );
}
